name: build
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scanners: 'misconfig'
        scan-ref: '.'
        hide-progress: false
        format: 'table'
        ignore-unfixed: true

         - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
          tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Pull WordPress Docker image
        run: docker pull wordpress:latest

      - name: Scan WordPress Docker image with Trivy
        run: trivy --severity HIGH,CRITICAL --no-progress wordpress:latest

