name: build
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scanners: 'misconfig'
        scan-ref: '.'
        hide-progress: false
        format: 'table'
        ignore-unfixed: true

    - name: Pull WordPress Docker image
      run: docker pull wordpress:latest

    - name: Scan WordPress Docker image with Trivy
      run: trivy --severity HIGH,CRITICAL --no-progress wordpress:latest

  analyze:
    name: Analyze code for SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup CodeQL
        uses: github/codeql-action/setup@v1
        with:
          languages: all

      - name: Analyze code
        uses: github/codeql-action/analyze@v1
